### ISSUE TITLE
Update "Learn more" prompts within AME wizard 

### ISSUE THREAD

**Issue by BJack0** [Atlas-OS/docs#132]
The AME wizard is directing the user to an unavailable docs page, the documentation for these options exists they have just moved.

**Comment by Anbiona** [comment]
I submitted a pull request on the atlas repository, this should be fixed soon.

**Comment by Anbiona** [comment]
Fixed: https://github.com/Atlas-OS/Atlas/pull/953

**Comment by Ast3risk-ops** [comment]
@BJack0 Please close this issue when possible.

**Comment by BJack0** [comment]
Mb :)
