### ISSUE TITLE
Non existent link

### ISSUE THREAD

**Issue by IdkAnythin07** [Atlas-OS/docs#16]
https://docs.atlasos.net/Getting%20started/Drivers/GPU/Intel
https://docs.atlasos.net/Getting%20started/Drivers/GPU/NVIDIA/Installation
https://docs.atlasos.net/Getting%20started/Drivers/GPU/AMD/Installation
404 not found

**Comment by PencilNavigator** [comment]
https://docs.atlasos.net/Getting%20started/Post-Installation//Drivers/GPU/Intel
https://docs.atlasos.net/Getting%20started/Post-Installation//Drivers/GPU/NVIDIA/Installation
https://docs.atlasos.net/Getting%20started/Post-Installation//Drivers/GPU/AMD/Installation
incorrect link.

**Comment by IdkAnythin07** [comment]
> https://docs.atlasos.net/Getting%20started/Post-Installation//Drivers/GPU/Intel https://docs.atlasos.net/Getting%20started/Post-Installation//Drivers/GPU/NVIDIA/Installation https://docs.atlasos.net/Getting%20started/Post-Installation//Drivers/GPU/AMD/Installation incorrect link.

these links were in https://docs.atlasos.net/Getting%20started/Post-Installation/Drivers/
