### ISSUE TITLE
'Removed Features' page should be converted into a full list of changes

### ISSUE THREAD

**Issue by he3als** [Atlas-OS/docs#174]
Currently the **Removed Features** page is not very descriptive, and a formatted page of changes should be completed to be more transparent with users. By formatting, I mean making the page have different headings for different categories of tweaks, like removals, QoL changes, etc...

Each YAML file inside of the Atlas playbook has a description and title, which can be used to aid in this.

**Comment by Ast3risk-ops** [comment]
So this would be one page with a bunch of headings and subheadings? It seems like there's a lot to cover.

**Comment by he3als** [comment]
I might do it with tabs, but probably headings.

**Comment by Ast3risk-ops** [comment]
> I might do it with tabs, but probably headings.

You should do it. 🥺

**Comment by Ast3risk-ops** [comment]
@he3als https://prebook.asterisk.lol/faq/features/ something like this?

**Comment by he3als** [comment]
It could be automatically generated to a degree due to all of the YAML files in the Playbook having descriptions and titles, but I'm not sure.

**Comment by Ast3risk-ops** [comment]
> It could be automatically generated to a degree due to all of the YAML files in the Playbook having descriptions and titles, but I'm not sure.

Yeah but in terms of layout

**Comment by Ast3risk-ops** [comment]
I'm sure the almighty 🦆 can handle such a task.

**Comment by he3als** [comment]
The 'Removed Features' page was rewritten. It's not a complete changes list, but I think it's good enough, so I'll close this.

**Comment by SkipeckiY** [comment]
9hAhZ6iik

**Comment by SkipeckiY** [comment]
Test
