### ISSUE TITLE
Installation doc + missing access to protected directory "WindowsApps"

### ISSUE THREAD

**Issue by Svan987** [Atlas-OS/docs#175]
[Packages.txt](https://github.com/Atlas-OS/docs/files/14044481/Packages.txt)

Install was done on a fresh Windows 11 Pro 22631.3007

As you can see in attached log several packages directory are unable to be deleted.

Need to add to "Atlas Documentation" - "Install Atlas OS", the instructions to give ownership to this hidden and protected directory
 "C:\Program Files\WindowsApps" (replace owner on subcontainers and objects too) before installing Atlas OS.

**Comment by Ast3risk-ops** [comment]
This is a unique issue, I do not believe it warrants docs modifications. Please ensure you actually did a correct install.

**Comment by Ast3risk-ops** [comment]
AME requires admin rights to launch at all.

Still, please test this on the dev playbook.

**Comment by JayXTQ** [comment]
Doesn't AME literally have access to the kernel too? so this issue doesn't make sense, especially for it to be in the docs repo.

**Comment by Ast3risk-ops** [comment]
Yeah wrong repo for sure.

**Comment by Ast3risk-ops** [comment]
> AME was launched with admin rights even it's not written in doc.

AME always launches with admin rights.

**Comment by Ast3risk-ops** [comment]
I'm on Linux, I can dump it from my VM later.

**Comment by Ast3risk-ops** [comment]
Upon further inspection of your document, all the errors are coming from removing one app, `MicrosoftWindows.Client.WebExperience`.

**Comment by Ast3risk-ops** [comment]
@JayXTQ You can close this.

@Svan987 Yeah always update windows first.
