### ISSUE TITLE
Error 404 in docs (invalid link for GPU drivers)

### ISSUE THREAD

**Issue by Muki-tech** [Atlas-OS/docs#18]
![IMG_4180](https://user-images.githubusercontent.com/59793198/229351121-d2d2e543-35fd-4199-af79-e1d28621dbc8.jpeg)
![IMG_4179](https://user-images.githubusercontent.com/59793198/229351124-ae555a16-5fb8-486a-952e-c9d0f9d01403.png)

**Comment by JayXTQ** [comment]
Thank you, will fix now!
