### ISSUE TITLE
How to use to check for latest apps and select apps to update?

### ISSUE THREAD

**Issue by candrapersada** [Atlas-OS/docs#233]
how to check the old version number of the installed application and the latest version number?
![image](https://github.com/user-attachments/assets/fa05fa5b-fe1c-4a95-8fbc-ecca1e3c67a6)

**Comment by Ast3risk-ops** [comment]
right click the start button, then choose `Windows PowerShell`. Once the prompt loads, type `winget upgrade` to show all app updates.
