### ISSUE TITLE
Windows 24H2

### ISSUE THREAD

**Issue by overwatch3560** [Atlas-OS/docs#236]
I've accidentally reinstalled windows 11 and now I have 24h2 and when trying to install atlas it says this build is not supported please add support for this build with version 0.5

**Comment by Ast3risk-ops** [comment]
The team is aware. Get 23h2 somehow or wait for 0.5.

**Comment by overwatch3560** [comment]
@Ast3risk-ops is there already a release date or still unknown?

**Comment by Ast3risk-ops** [comment]
Unknown, join the discord for details.
