### ISSUE TITLE
cant download windows 11 23h2 iso file

### ISSUE THREAD

**Issue by biskyy** [Atlas-OS/docs#238]
i get the following error message when trying to download w11 23h2 iso file: Error: ISO_LINK_NOT_DEFINED

this is what console shows on arc:![image](https://github.com/user-attachments/assets/0ce53fa6-c87a-4d77-8931-ca1478a8bf52)

**Comment by PencilNavigator** [comment]
Microsoft changed something on their end after the 24H2 release, making MSDL unable to get the 23H2 ISO download link. (24H2 links are fine)

We are working on a new playbook release that supports 24H2 and will be fixing this together.

**Comment by biskyy** [comment]
bruuuh that sucks :p. thx for explaining. does anyone happen to know another safe place to get the iso file?

**Comment by PencilNavigator** [comment]
Unfortunatly we cannot provide nor host an unofficial download link. The Microsoft EULA has limited us from doing that.

**Comment by wh0isrh** [comment]
> Unfortunatly we cannot provide nor host an unofficial download link. The Microsoft EULA has limited us from doing that.

Maybe some1 else can :P

**Comment by wh0isrh** [comment]
*Please :)

**Comment by Ast3risk-ops** [comment]
> > Unfortunatly we cannot provide nor host an unofficial download link. The Microsoft EULA has limited us from doing that.
> 
> Maybe some1 else can :P

https://cpaste.org/?4bb5c15d10a1c35c#GQDGhgQhr6fDe5atY94BRra9FpYgCULum4xu56P1t9B7

@wh0isrh you know this password, it's the only thing on github you show off.

> This was done on my own volition

**Comment by he3als** [comment]
It's 24H2 now with v0.4.1
