### ISSUE TITLE
Download Links For The AtlasOS (Win10/Win11) Not Working 

### ISSUE THREAD

**Issue by bertonumber1** [Atlas-OS/docs#244]
Hi Guys,
I read the documentation after stumbling upon your site.
Finally went to install and am met with:

"An error has occurred while processing your request. Try refreshing the page or using an alternative method.

Error: HTTP_FAILED_TO_GET_LANGS

This error is evident when clicking on both win11 and win10 download buttons and i suspect is maybe an api related error when the iso download language is being queried by Microsoft or wherever the iso is sourced. This is just a guess.

This same thing happens on three different pc and laptops and have tried safari, chrome, brave and via browsers all with the same results.

Hope you are good and know your time and work are appreciated 

Many Thanks 

Regards 

Berto

**Comment by Ast3risk-ops** [comment]
MSDL is currently offline, you can get windows 11 from the official download page and windows 10 from the media creation tool.

**Comment by PencilNavigator** [comment]
MSDL is broken. Please use our alternative method mentioned on docs.
https://docs.atlasos.net/getting-started/installation/#1-download-an-iso
https://github.com/Atlas-OS/docs/commit/1c9e34f97ac570a838dcb0288f18e94564b30247
