### ISSUE TITLE
ATLAS DOCUMENTATION ISSUE

### ISSUE THREAD

**Issue by bandinfinite** [Atlas-OS/docs#27]
I double-clicked on the must read first file. And it said page ain't found. I'm unaware of any changes made by the dev's.
![image](https://user-images.githubusercontent.com/119771087/231743306-ee89d63a-45b0-4167-984a-dd5ecd4bc550.png)
![image](https://user-images.githubusercontent.com/119771087/231743346-ddd2fbbf-2d29-45e6-9109-8f14d7f73f6f.png)

**Comment by JayXTQ** [comment]
Can you show us where this button is because this issue can’t be fixed without us doing a full search for it. For now you can manually find the page in the menus given.

**Comment by bandinfinite** [comment]
It ain't a button. It is a file. I have sent ss of the explorer. The last file is the file I clicked upon

**Comment by bandinfinite** [comment]
Yeah

**Comment by JayXTQ** [comment]
@Xyueta I am still not home, can you fix this and close the issue when solved. Thanks

**Comment by JayXTQ** [comment]
Yes, was very helpful. Will be fixed in the next atlas release.

**Comment by Xyueta** [comment]
https://github.com/Atlas-OS/Atlas/commit/206d81d3bebd32cc0ef14d564a84311c86fff498
