### ISSUE TITLE
Distorted Mobile View

### ISSUE THREAD

**Issue by pewpewded** [Atlas-OS/docs#33]
**Mobile display appears to be distorted on:**

https://atlasos.net/downloads/w10_22h2

This can be easily fixed by adding the `word-wrap: break-word;` property to the `<p>` tag that contains the hash function.

**Current behavior:**

![distorted image](https://user-images.githubusercontent.com/118110192/233433155-75e4c325-469c-42d3-b6fb-4d67c552a504.png)

**Proposed fix:**

![fixed image](https://user-images.githubusercontent.com/118110192/233433438-415a8b32-4bbf-4d8b-aba1-25c2b4ce0262.png)

**Comment by pewpewded** [comment]
i apologize for opening the issue here;

![image](https://user-images.githubusercontent.com/118110192/233434355-d59cf2c4-b5e5-4b06-9674-3dc1c822ed10.png)

**Comment by pewpewded** [comment]
Also, if you guys ever want help with any of the websites, i would be happy to contribute!

**Comment by SyrmGIT** [comment]
Thank you for the issue. I've pushed the solution!
