### ISSUE TITLE
Error 404 for link that redirects to Disable Multiplane Overlay (MPO)

### ISSUE THREAD

**Issue by Muki-tech** [Atlas-OS/docs#44]
![IMG_4601](https://user-images.githubusercontent.com/59793198/234084838-ef27d14e-682f-4de1-8105-473e159e59cc.jpeg)
![IMG_4602](https://user-images.githubusercontent.com/59793198/234084846-af6ebc62-c57e-4bbe-b2df-9bd007a2bb68.png)

**Comment by Xyueta** [comment]
thanks, I am gonna fix it now.
