### ISSUE TITLE
C:\Users\USER\Desktop\Atlas\4. Troubleshooting\Services "Default Atlas drivers.reg" and "Default Windows drivers.reg" are fully blank

### ISSUE THREAD

**Issue by Wonderingg** [Atlas-OS/docs#45]
![image](https://user-images.githubusercontent.com/83306625/234088414-dec7ff80-a311-472f-913e-bc8b2e088834.png)
![image](https://user-images.githubusercontent.com/83306625/234088447-4f0b1302-dd2d-4fdd-a74b-f2ed1e2d3c5f.png)

**Comment by JayXTQ** [comment]
Hi, this is the docs repository, please use the main repository for this issue!
