### ISSUE TITLE
Non usb installation doc

### ISSUE THREAD

**Issue by thameur96** [Atlas-OS/docs#47]
The non usb installation guide is not found "404"

**Comment by JayXTQ** [comment]
Can you elaborate please? Like where are you clicking the link that makes it a 404?

**Comment by elrac** [comment]
All of the links on the left side of this page https://docs.atlasos.net/Getting%20started/Installation/ return a 404. 

https://docs.atlasos.net/Getting%20started/Other%20installation%20methods/No%20USB/
https://docs.atlasos.net/Getting%20started/Post-Installation/Drivers/
https://docs.atlasos.net/Getting%20started/Post-Installation/Configuration/
https://docs.atlasos.net/Getting%20started/Post-Installation/Software/
https://docs.atlasos.net/Getting%20started/Post-Installation/Activate%20Windows/

![image](https://user-images.githubusercontent.com/4564119/234119085-a2c0ccd0-a074-4596-b1d5-6d28e21a9435.png)

**Comment by Xyueta** [comment]
Please clear your cache. It should be cleaned now.

**Comment by elrac** [comment]
it is indeed working, thank you
