### ISSUE TITLE
Wrong link for No USB installation

### ISSUE THREAD

**Issue by ammaraziz** [Atlas-OS/docs#49]
Hi there,

On this page:
https://docs.atlasos.net/Getting%20started/Installation/

The `No USB` link is:

```
https://docs.atlasos.net/Getting%20started/Other%20installation%20methods/No%20USB/
```
Note the spaces `%20`. The link should be:

```
https://docs.atlasos.net/getting-started/other-installation-methods/no-usb/
```

Thanks for creating this! Super cool project.

Related to this pull request: https://github.com/Atlas-OS/docs/pull/37

**Comment by CreepTron365** [comment]
Just tried it on the website. Can second this issue.

**Comment by ammaraziz** [comment]
Another one:
https://github.com/Atlas-OS/docs/blob/4224b27d3e982f0bf591efdc72bc9706f06c903d/docs/getting-started/other-installation-methods/no-usb.md?plain=1#L15

**Comment by JayXTQ** [comment]
Hi, this issue is to do with cloudflare. The issue shouldn’t be there since the PR. Please only use URLs that contain - and not %20, also no capitals!
