### ISSUE TITLE
problem with nvidia control panel

### ISSUE THREAD

**Issue by Nairolf3** [Atlas-OS/docs#67]
Hello, I followed all the instructions in order until the installation of the drivers.
I installed the nvidia driver with nvcleaninstall following the instructions.
I can no longer open the nvidia control panel.
I tried everything, I uninstalled it with iobit to reinstall it, I redid a complete installation with the driver from the nvidia site.
And it doesn't work again.
Thanks for your help

![image](https://user-images.githubusercontent.com/118687033/235651148-5afdfa4c-66b9-4721-91b3-9758732f43db.png)
![image](https://user-images.githubusercontent.com/118687033/235651948-7c4eb370-bef6-458e-80ad-0be2a7917f1a.png)
![image](https://user-images.githubusercontent.com/118687033/235652039-34028da0-4a99-4649-b0f1-c3ecb631c979.png)

**Comment by JayXTQ** [comment]
wrong repository.
