### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by he3als** [Atlas-OS/docs#73]
What should the license for this repository be?

**Comment by PencilNavigator** [comment]
CC-BY-SA

**Comment by JayXTQ** [comment]
Pencil, link the document of what that is

**Comment by he3als** [comment]
He edited the message, I agree that CC-BY-SA-4.0 would be good.

**Comment by PencilNavigator** [comment]
it's simliar to gpl which main repo uses but for non-code purposes.

**Comment by PONGSATHONSAMAEUN** [comment]
CC-BY-SA-4.0

**Comment by JayXTQ** [comment]
Pencil just said that bri

**Comment by PencilNavigator** [comment]
i recommend dual license, AGPL-3.0 and CC-BY-SA-4.0, AGPL for code related, CC for content related

**Comment by PONGSATHONSAMAEUN** [comment]
he3als

**Comment by PencilNavigator** [comment]
say things in full sentence, thanks.

**Comment by JayXTQ** [comment]
I think one license is good enough

**Comment by he3als** [comment]
> i recommend dual license, AGPL-3.0 and CC-BY-SA-4.0, AGPL for code related, CC for content related

There's not much code really in comparison, I don't think that a dual license would be needed and it would only complicate things really. I think that `CC-BY-SA-4.0` is applicable.

**Comment by PencilNavigator** [comment]
CC licenses aren't suppose to use for code related stuff.

**Comment by PencilNavigator** [comment]
https://github.com/PencilNavigator/docs
preview here

**Comment by whallin** [comment]
The dual licenses approach might seem reasonable in practice. Still, it really won't be beneficial as we (1) don't ship any own code in this repository and (2) this repository doesn't contain any software, where AGPL is a software license, as we know.

Stick to one license as long as we don't ship code. I agree with CC-BY-SA-4.0.
