### ISSUE TITLE
128k cluster size - DirectX 2010

### ISSUE THREAD

**Issue by KiralyCraft** [Atlas-OS/docs#79]
I have installed my machine with a 128k cluster size for C:\. It's my first time running Atlas, according to the instructions. It seems that DirectX 2010 is not happy about the cluster size being 128k, and therefore refuses to install. It opened in the background, as my resolution was 800 x 600, and couldn't see behind the installer. It was only after closing it that I noticed DirectX's message.

My installation was stuck at "Reticulating splines", and to my surprise, the troubleshooting guide didn't help, as the problem was not yet documented. 

I'm not sure what the best course of action would be here, either warn against this possible issue or fail installation.

**Comment by JayXTQ** [comment]
wrong repository.
