### ISSUE TITLE
Post-installation not linked correctly.

### ISSUE THREAD

**Issue by MRCattos** [Atlas-OS/docs#82]
The "post-installation" is not linked correctly at the bottom of the this page: https://docs.atlasos.net/getting-started/installation/#install-atlas. I don't know what it's supposed to be since there is no "post installation" page so that's why I post it here as a issue. 
Here are a couple screenshots so you can see what i mean.
![image](https://github.com/Atlas-OS/docs/assets/91627447/b8b6848d-6d31-46a1-918d-90f1ff91c096)
![image](https://github.com/Atlas-OS/docs/assets/91627447/3080491f-d108-455b-808f-e188474c6f73)

Going back to post-installation page via this page https://docs.atlasos.net/getting-started/post-installation/drivers/ also doesn't work but that is because they page doesn't exist.
![image](https://github.com/Atlas-OS/docs/assets/91627447/60a7d451-9735-4f8f-aa41-4c4343816152)

**Comment by JayXTQ** [comment]
Hi, thanks for the issue report. If you wish you can make a PR to fix this issue or I will fix it later

**Comment by MRCattos** [comment]
I'll make a pr in a couple minutes
